// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Basket struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

type Delivery struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CourierID uuid.UUID
	OrderID   uuid.UUID
}

type Order struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	BasketsID        []uuid.UUID
	Address          string
	AddressLocationX float64
	AddressLocationY float64
	PickUpLocationX  float64
	PickUpLocationY  float64
	Metadata         string
	TotalPrice       float64
	CreatedAt        time.Time
	StartedAt        sql.NullTime
	DeliveredAt      sql.NullTime
	Status           string
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       sql.NullFloat64
	Quantity    int32
}

type User struct {
	ID           uuid.UUID
	Name         string
	Surname      string
	Phone        string
	Login        string
	PasswordHash string
	Role         string
	Address      string
	LocationX    float64
	LocationY    float64
}
