// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const GetUser = `-- name: GetUser :one
SELECT u.id, u.name, u.surname, u.phone, u.role, u.address, u.location_x, u.location_y FROM users u
WHERE u.id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	Name      string
	Surname   string
	Phone     string
	Role      string
	Address   string
	LocationX float64
	LocationY float64
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, GetUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Phone,
		&i.Role,
		&i.Address,
		&i.LocationX,
		&i.LocationY,
	)
	return i, err
}
